const projects = [
  {
    id: 1,
    name: "Landing page of NITAD website",
    photo: "/src/assets/nitad.png",
    code: "https://github.com/dandytech/NITAD",
    site: "https://dandy-nitad.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
      "/src/assets/bootstrap.jpeg",
    ],
  },
  {
    id: 2,
    name: "Landing page of Producemart website",
    photo: "/src/assets/producemart.png",
    code: "https://github.com/dandytech/producemart",
    site: "https://dandy-producemart.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
      "/src/assets/bootstrap.jpeg",
    ],
  },
  {
    id: 3,
    name: "Landing page of Primeparkland website",
    photo: "/src/assets/primeparkland.png",
    code: "https://github.com/dandytech/primeparkland",
    site: "https://dandy-primeparkland.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
      "/src/assets/bootstrap.jpeg",
    ],
  },
  {
    id: 4,
    name: "Landing page of CRAPPO Crypto website",
    photo: "/src/assets/crypto.png",
    code: "https://github.com/dandytech/crypto",
    site: "https://dandy-crypto.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
    ],
  },
  {
    id: 5,
    name: "Dashboard for Product Sales Firm",
    photo: "/src/assets/dashboard.png",
    code: "https://github.com/dandytech/dashboard",
    site: "https://dandy-dashboard.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
      "/src/assets/bootstrap.jpeg",
    ],
  },
  {
    id: 6,
    name: "Admin Dashboard for Lagos Business School",
    photo: "/src/assets/dashboard1.png",
    code: "https://github.com/dandytech/adminDashboard",
    site: "https://dandy-dashboard1.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
      "/src/assets/bootstrap.jpeg",
    ],
  },
  {
    id: 7,
    name: "Input Validation/verification Page",
    photo: "/src/assets/inputverify.png",
    code: "https://github.com/dandytech/inputConfirm",
    site: "https://dandy-inputverification.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/js.jpeg",
    ],
  },
  {
    id: 8,
    name: "Nexted Registration forms",
    photo: "/src/assets/nextedreg.png",
    code: "https://github.com/dandytech/nextedreg",
    site: "https://dandy-nextedreg.netlify.app/",
    stack: [
      "/src/assets/html.jpeg",
      "/src/assets/css.jpeg",
      "/src/assets/bootstrap.jpeg",
    ],
  },
  {
    id: 9,
    name: "Digital Architecture unscroll Page",
    photo: "/src/assets/digitalarch.png",
    code: "https://github.com/dandytech/digitalarch",
    site: "https://dandy-digitalarch.netlify.app/",
    stack: ["/src/assets/html.jpeg", "/src/assets/css.jpeg"],
  },
];
export default projects;
